### ISSUE TITLE
gruvbox gruvbox_sign_column

### ISSUE THREAD

**Issue by lanox** [gruvbox-community/gruvbox#133] opened 2020-05-08 05:05 UTC
Hi all,

Just curious as to why this option doesn't work `set let g:gruvbox_sign_column='bg4'`

Have added it in init.vim but nothing happens also if I try setting that my self from vim, I see that option come up in the floating window, see image below
<img width="446" alt="Screen Shot 2020-05-08 at 2 04 34 pm" src="https://user-images.githubusercontent.com/7599183/81372217-264f8680-913d-11ea-934f-b3a4b47a346e.png">

my init.vim
```
call plug#begin('~/.config/nvim/plugged')
Plug 'gruvbox-community/gruvbox'
Plug 'scrooloose/nerdtree'
call plug#end()

set termguicolors                                           " Enable True Color support.
let g:airline_theme='gruvbox'
let g:gruvbox_sign_column='bg4'
colorscheme gruvbox
```
Thanks.

**Comment by rbong** [comment] 2020-05-08 11:16
In both vim and nvim, when I use your example configuration, when i use your config, this is the result:

```
:hi SignColumn
guibg=#7c6f64
```

When I don't enable it, I get `guibg=#3c3836`.

In addition, I can see the correct color when I use `:set signcolumn=yes`.

Note that if you're using `g:gitgutter_override_sign_column_highlight` normally, it overwrites the option.

What do you get when you use `:hi SignColumn` and `:set signcolumn=yes`?

**Comment by lanox** [comment] 2020-05-08 11:33
Hi @rbong  thanks for getting back,

I get `SignColumn xxx ctermbg=237 guibg=#3c3836`
<img width="106" alt="Screen Shot 2020-05-08 at 9 32 17 pm" src="https://user-images.githubusercontent.com/7599183/81401793-66316080-9173-11ea-8b68-7d41b4e8d70c.png">

what I am trying to do is to change the SignColumn to be the same colour as the rest of the screen.

**Comment by rbong** [comment] 2020-05-08 12:16
@lanox I notice the screenshot is not using your minimal config so I have to ask, do you get the same result for `:hi SignColumn` even with your minimal config?

**Comment by lanox** [comment] 2020-05-08 12:18
@rbong sorry I am flipping between my config and minimal trying to work out why it is not working.

But yes the result is the same. 

What do you get  when you do it on your side ?

**Comment by lanox** [comment] 2020-05-08 12:28
It is very strange I have removed my entire nvim dir from .config and just using minimal config, and still the same.

**Comment by rbong** [comment] 2020-05-08 12:42
I get `guibg=#7c6f64`.

>I have removed my entire nvim dir from .config

That's good, I was going to ask that. Some more questions:

What's your result for `:echo g:gitgutter_override_sign_column_highlight`?

If you use `let g:gruvbox_number_column = 'bg4'` instead of `g:gruvbox_sign_column`, does it set the color appropriately?

What result do you get for `nvim --version`?

Is the problem fixed after doing `:PlugUpdate`? What is the result for `:PlugSnapshot`?

**Comment by lanox** [comment] 2020-05-08 12:45
```
NVIM v0.5.0-deb4566
Build type: Release
LuaJIT 2.0.5
```
:echo g:gitgutter_override_sign_column_highlight -> I get Undfined variable: g:gitgutter_override_sign_column_highlight

`let g:gruvbox_number_column = 'bg4'` nah nothing.

**Comment by rbong** [comment] 2020-05-08 12:51
Is it fixed with `:PlugUpdate`? What's the result for `:PlugSnapshot`?

**Comment by lanox** [comment] 2020-05-08 12:54
Unfortunately no, sorry forgot to say that

**Comment by rbong** [comment] 2020-05-08 12:59
What's the result of `:PlugSnapshot`? Sorry just trying to make sure we have the same version installed.

**Comment by lanox** [comment] 2020-05-08 13:03
No Problems at all thankyou for helping.
```
Generated by vim-plug
" Fri  8 May 23:02:08 2020
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim
silent! let g:plugs['gruvbox'].commit = '268267d'
 PlugUpdate
```

**Comment by rbong** [comment] 2020-05-08 13:12
Thank you. Just wondering, is `nerdtree` required to reproduce this problem? It was in your minimal config but not in your snapshot.

**Comment by lanox** [comment] 2020-05-08 13:13
I even removed nerdtree just to be safe, I can put it back in therel if you like, this is so weird.

**Comment by rbong** [comment] 2020-05-08 13:15
That's okay, if it still happens without nerdtree that narrows it down. I was hoping that would be it though. This is definitely weird. One more question for complete reproducability because this problem is so strange - what OS are you using?

**Comment by lanox** [comment] 2020-05-08 13:16
macos 10.15.4

**Comment by lanox** [comment] 2020-05-08 14:44
So this is a little weird, I changed `let s:sign_column = s:gb.bg1` to `let s:sign_column = s:gb.dark0_hard` in gruvbox.vim and signcolumn changed he colour.

**Comment by lanox** [comment] 2020-05-08 22:25
@rbong any other thoughts? 

Also if you set it to the colour I did in my above comment do you see colour change?

**Comment by lanox** [comment] 2020-05-09 03:25
@rbong Okay so I definitely can confirm that there is something up with this version of gruvebox as I am able to change singcolumn as well as Number column in original gruvbox theme.

<img width="131" alt="Screen Shot 2020-05-09 at 1 21 19 pm" src="https://user-images.githubusercontent.com/7599183/81462721-fa450b80-91f7-11ea-8de9-d837033d1862.png">
<img width="361" alt="Screen Shot 2020-05-09 at 1 21 33 pm" src="https://user-images.githubusercontent.com/7599183/81462731-029d4680-91f8-11ea-8854-56e8109f087c.png">

my config currently with original theme

```
call plug#begin('~/.config/nvim/plugged')
Plug 'morhetz/gruvbox'
call plug#end()

set termguicolors                                           " Enable True Color support.
let g:airline_theme='gruvbox'
let g:gruvbox_contrast_dark='medium'
let g:gruvbox_number_column='red'
let g:gruvbox_sign_column='dark0_hard'
colorscheme gruvbox
```

**Comment by lanox** [comment] 2020-05-09 03:37
If I replace this code in community gruvbox 
```
if exists('g:gruvbox_sign_column')
  let s:sign_column = get(s:gb, g:gruvbox_sign_column)
endif
```
with code below from original gruvbox it works fine.
```
if exists('g:gitgutter_override_sign_column_highlight') &&
      \ g:gitgutter_override_sign_column_highlight == 1
  let s:sign_column = s:number_column
else
  let g:gitgutter_override_sign_column_highlight = 0

  if exists('g:gruvbox_sign_column')
    let s:sign_column = get(s:gb, g:gruvbox_sign_column)
  endif
endif
```

**Comment by rbong** [comment] 2020-05-09 09:29
Those two blocks of code should be functionally identical since `g:gitgutter_voerride_sign_column_highlight` shouldn't be set.
Even if that value was set, the highlight for the sign column would be read from `g:gruvbox_number_column`, and you wouldn't be able to use the `g:gruvbox_sign_column` variable to change the highlight group.
Even if you have THAT variable set, it's never read any differently than `g:gruvbox_sign_column`, and the `SignColumn` highlight group is not set any differently, so it doesn't explain the bug.

Since you have none of these variables set and gruvbox never touches them outside of this small chunk of code I have to assume it's some bizarre environmental issue.

This is all to say that I cannot recreate this issue, and there's no indication of what the bug is just by switching out that code. Your best bet is to look at what's going on internally.

You can check which plugins are actually being loaded with this command:

```
nvim --startuptime startup.txt
```

Then you can quit out of nvim and read `startup.txt` to look at which files are actually being read.

Outside of that I would add `:echo` commands to trace what's going on, for example to that same chunk of code to see what the actual value is of `g:gruvbox_sign_column` is when it gets there to see if it's overriding it afterwards or never getting the variable at all.

```
echo "SIGN COLUMN CONFIG:" g:gruvbox_sign_column

if exists('g:gruvbox_sign_column')
  let s:sign_column = get(s:gb, g:gruvbox_sign_column)
endif

echo "SIGN COLUMN FINAL VALUE:" s:sign_column
```

Also, you can always try this workaround although it is not ideal, where `#000000` is the background you want:

```
autocmd ColorScheme gruvbox hi SignColumn guibg=#000000
```

**Comment by rbong** [comment] 2020-05-09 09:40
Oh yes, and the one thing that line of code functionally does differently is this:

```
let g:gitgutter_override_sign_column_highlight = 0
```

Which should not impact anything unless if you have gitgutter enabled, which you shouldn't because you cleaned out your nvim directory.
The variable is never referenced in gruvbox again.
On top of that it would have to be an old version, since the variable is utterly obsoleted: https://github.com/airblade/vim-gitgutter/issues/704

Even if that were the case, since the option is disabled, it should not work differently, unless if the old version of gitgutter has a bug.

All signs point again to a more bizarre issue than a code error, unless if I am reading the code wrong and these lines from the two snippets you've posted are not in fact identical or I am missing something about how they are executed:

```
if exists('g:gruvbox_sign_column')
  let s:sign_column = get(s:gb, g:gruvbox_sign_column)
endif
```

```
  if exists('g:gruvbox_sign_column')
    let s:sign_column = get(s:gb, g:gruvbox_sign_column)
  endif
```

**Comment by lanox** [comment] 2020-05-09 09:52
Hrm I dunno, I will check when I get to my computer.

However , I do find it weird that even after removing my entire dotfiles directory resetting iterm2 to default and only having minimal vim  it still didn’t work. But if I used original gruvbox it is working fine on my config as well as clean config.

**Comment by rbong** [comment] 2020-05-09 10:03
If it is working when using the original gruvbox that could narrow it down to a problem between the two versions, but if switching out that small chunk of code is changing something it looks more like an external issue. Make sure that if you're testing with `gruvbox-community/gruvbox` and you're changing out that small chunk of code, you're not accidentally loading `morhetz/gruvbox` instead.

**Comment by lanox** [comment] 2020-05-09 10:14
So I am not at my computer, but while I was trying to figure out this is what I did:

1. Remove my dotfiles clean profile in iterm2
2. Remove entire .config/nvim 
3. Then just installed minimal config with original gruvbox tested it and worked

Then

1. Remove .config/nvim dir and do it again but with community version and didn’t work.

Then I tried changing code around like in my previous post.

**Comment by lanox** [comment] 2020-05-09 14:42
@rbong so I worked it out, but I am not understanding why it matters.

```
set background=dark
let g:airline_theme='gruvbox'
let g:gruvbox_sign_column='red'
colorscheme gruvbox
````

so If I have `colorscheme` above `let g:gruvbox_sign_column='red'` it will not work, as soon as I move the `colorscheme` below `let g:gruvbox_sign_column='red'` all works fine, so it seems that colorschme needs to be at the bottom of all  optional settings.

**Comment by rbong** [comment] 2020-05-09 15:41
`colorscheme gruvbox` loads the `colorscheme/gruvbox.vim` file, so all settings need to go before that. Glad you got it worked out.

**Closed by rbong** 2020-05-09 15:41 UTC
